### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by keab42** [deltaDNA/ios-sdk#1]
Could you maybe make the changelog a bit more detailed?

**Comment by dwxw** [comment]
I will once there's some changes from the initial release.

**Comment by keab42** [comment]
So there are no changes from 3.5.4 to 4.0?

**Comment by dwxw** [comment]
We’re in the process of adding a migration guide from 3.x to 4.x to our docs site <http://docs.deltadna.com/advanced-integration/ios-sdk/>.

> On 24 Mar 2016, at 10:27, Matthew Keable <notifications@github.com> wrote:
> 
> So there are no changes from 3.5.4 to 4.0?
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub <https://github.com/deltaDNA/ios-sdk/issues/1#issuecomment-200776540>


-- 
 
<https://deltadna.com/contact-us/?utm_source=email&utm_medium=email&utm_content=Meet_At_Event&utm_campaign=Sales>


<https://www.linkedin.com/company/deltadna> 
<https://www.facebook.com/deltaDNA> <https://twitter.com/deltaDNA> 
<https://plus.google.com/+Deltadna/posts>

Disclaimer: This email and any attachments are confidential and intended 
for the addressee only. If you are not the named recipient, you must not 
use, disclose, reproduce, copy or distribute the contents of this 
communication. If you have received this in error, please contact the 
sender and then delete this email from your system. DeltaDNA is registered 
in Scotland with the registration number SC383152. The registered office is 
situated at 25 Greenside Place, Edinburgh EH1 3AA Scotland.
